plugins {
	id 'fabric-loom' version "${loom_version}"
}

dependencies {
	implementation project(':base')
	minecraft group: 'com.mojang', name: 'minecraft', version: project.minecraft_version
	mappings loom.officialMojangMappings()
	modImplementation group: 'net.fabricmc', name: 'fabric-loader', version: project.loader_version

	modImplementation fabricApi.module('fabric-api-base', project.fabric_api_version)
	modImplementation fabricApi.module('fabric-lifecycle-events-v1', project.fabric_api_version)
	modImplementation fabricApi.module('fabric-command-api-v1', project.fabric_api_version)
}

loom {
	mixin {
		useLegacyMixinAp = false
	}
}

processResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('fabric.mod.json') {
		expand inputs.properties
	}
}
