name: ChatModerator
version: ${version}
main: vakiliner.chatmoderator.bukkit.ChatModeratorPlugin
description: Модерация игроков в чате
author: VAKiliner
website: https://github.com/vakiliner/ChatModerator
api-version: '1.13'
load: STARTUP
commands:
  mute:
    description: Заглушить игрока в чате
    permission: chatmoderator.command.mute
    usage: /mute <player_name> [<duration>] [<reason>]
  unmute:
    description: Снять с игрока мут
    permission: chatmoderator.command.unmute
    usage: /unmute <player_name>
  mutes:
    description: Показать список активных мутов
    permission: chatmoderator.command.mutes
    usage: /mutes [<page>]
default-permission: false
permissions:
  chatmoderator.*:
    description: Все разрешения для плагина ChatModerator
    children:
      chatmoderator.spectator_chat:
        description: Чат наблюдателя
        default: false
      chatmoderator.bypass_moderation.*:
        description: Обход модерации
        children:
          chatmoderator.bypass_moderation.mutes:
            description: Обход заглушения и автомода
            default: op
      chatmoderator.command.*:
        description: Все команды плагина ChatModerator
        children:
          chatmoderator.command.mute:
            description: Использование команды /mute
            default: op
          chatmoderator.command.unmute:
            description: Использование команды /unmute
            default: op
          chatmoderator.command.mutes:
            description: Использование команды /mutes
            default: op