name: ChatModerator
version: ${version}
main: vakiliner.chatmoderator.bukkit.ChatModeratorPlugin
description: Модерация игроков в чате
author: VAKiliner
website: https://github.com/vakiliner/ChatModerator
commands:
  mute:
    description: Заглушить игрока в чате
    permission: chatmoderator.mute
    usage: /mute <player_name> [<duration>] [<reason>]
  unmute:
    description: Снять с игрока мут
    permission: chatmoderator.mute
    usage: /unmute <player_name>
  mutes:
    description: Показать список активных мутов
    permission: chatmoderator.mute
    usage: /mutes [<page>]
default-permission: false
permissions:
  chatmoderator.*:
    description: Все разрешения для плагина ChatModerator
    children:
      chatmoderator.mute:
        description: Разрешение на глушение игроков в чате
        default: op
      chatmoderator.spectator_chat:
        description: Чат наблюдателя
        default: false
      chatmoderator.bypass_moderation.*:
        description: Обход модерации
        children:
          chatmoderator.bypass_moderation.mutes:
            description: Обход заглушения и автомода
            default: op