plugins {
	id 'java'
}

dependencies {
	implementation project(':base')
}

processResources {
	var replaceProperties = [
		version: project.version,
		license: project.license,
	]
	inputs.properties replaceProperties

	filesMatching('plugin.yml') {
		expand replaceProperties
	}
}

jar {
	exclude 'vakiliner/chatcomponentapi/spigot/**'
	exclude 'vakiliner/chatcomponentapi/paper/**'
	exclude 'vakiliner/chatmoderator/spigot/**'
	exclude 'vakiliner/chatmoderator/paper/**'
}
