plugins {
	id 'dev.architectury.loom' version "${loom_version}"
}

dependencies {
	implementation project(':base')
	minecraft group: 'net.minecraft', name: 'minecraft', version: project.minecraft_version
	mappings loom.officialMojangMappings()
	forge group: 'net.minecraftforge', name: 'forge', version: "${project.minecraft_version}-${project.forge_version}"
}

processResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

processTestResources {
	filesMatching('META-INF/mods.toml') {
		expand inputs.properties
	}
}

jar {
	manifest {
		attributes([
			MixinConfigs: 'mixins.chatcomponentapi.forge.json'
		])
	}
}
