version: -32765
max_message_length: 80
max_mute_reason_length: 50
spectators_chat: false
folder_path: null
mutes_file:
  path: mutes.json
  # Available: autodetect (Checks file extension in the name), json, jsonl.
  extension: autodetect
  # Available: recommended (Selects recommended library for file extensions), gson (for json & jsonl).
  library: recommended
  options:
    encoding: UTF-8
auto_moderation:
  enabled: true
  use_thread_pool: false
  rules_file:
    path: auto_moderation_rules.json
    extension: json
    library: gson
    options:
      encoding: UTF-8
dictionary_file:
  path: dictionary_ru.json
  extension: json
  library: gson
  options:
    encoding: UTF-8
show_fail_message: true
log_blocked_messages: false
log_blocked_commands: false
messages:
  fail_send_message: Ваше сообщение не было отправлено
  fail_send_command: Не удалось использовать команду
  fail_reasons:
    muted: Вы были ограничены
    muted_with_reason: |-
      Вы были ограничены
      Причина: %s
    cannot_use_msg_command_in_spectator: Наблюдатели не могут использовать команды отправки сообщений
    long_message: Слишком длинное сообщение
    automod_blocked_without_custom_message: Публикация невозможна, поскольку сообщение содержит материалы, заблокированные этим сервером. Владельцы сервера также могут просматривать содержимое сообщений.
    automod_blocked_with_custom_message: 'Содержимое сообщения заблокировано сервером. Сообщение от модераторов: «%s»'
