name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      release-sufix:
        type: string
        required: false
        description: В случае, если тэг релиза уже занят
      recommended:
        type: boolean
        required: true
        default: false
        description: Заменить рекомендуемые версии в update.json
jobs:
  release:
    name: Draft a new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
